export {default as Dashboard} from './Dashboard'
export {default as Department} from './Department'
export {default as Staff} from './Staff'
export {default as SignIn} from './SignIn'
export {default as SignUp} from './SignUp'